# Generated by Django 5.1.2 on 2024-10-25 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo_electronico', models.TextField(unique=True)),
                ('contraseña', models.TextField()),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pen', 'Pendiente'), ('Prog', 'Progreso'), ('Com', 'Completada')], default='Pendiente', max_length=10)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('hora_vencimiento', models.TimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.proyecto')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gtareas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200, unique=True)),
                ('tareas', models.ManyToManyField(related_name='tareas_asociadas', to='gtareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario', through='gtareas.AsignacionTarea', to='gtareas.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='proyectos_asignados', to='gtareas.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_contenido', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.tarea')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtareas.usuario')),
            ],
        ),
    ]
