# Generated by Django 5.1.2 on 2024-10-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='etiquetas',
            new_name='tareas',
        ),
    ]
